services:
  - type: web
    name: express-coursework-backend
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: ""          # Node services usually donâ€™t need this
    startCommand: node server.js
    healthCheckPath: /